development:
  adapter: postgresql
  encoding: unicode
  database: unifeso_development
  pool: 5
  username: rails
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: unifeso_test
  pool: 5
  username: rails
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: unifeso_production
  pool: 5
  username: rails
  password:
